### ISSUE TITLE
Implement view convention and formField view convention tests

### ISSUE THREAD

**Issue by cdaringe** [datuhealth/ampersand-floatinglabel-input-view#2]
https://github.com/AmpersandJS/ampersand-form-view/issues/28

**Comment by mike-engel** [comment]
@cdaringe, not sure what needs to get updated on our end. Are you asking for an update to our ampersand-input-view dependency or an update to our tests?

**Comment by cdaringe** [comment]
hey @mike-engel, we were going to add some additional requirements to formField conventions, but the request is to simply add https://github.com/AmpersandJS/ampersand-view-conventions to the test suite!  [example](https://github.com/AmpersandJS/ampersand-select-view/blob/master/test/index.js#L43)

**Comment by mike-engel** [comment]
Thanks @cdaringe. So, I've got it working, kind-of. It's a little weird since our tests are written in mocha, and ViewConventions.view() doesn't return anything on pass/fail, so it's hard to check if those tests pass/fail.

**Comment by mike-engel** [comment]
Really, just waiting for https://github.com/AmpersandJS/ampersand-view-conventions/pull/7 to be merged in before I can finally call this done.

**Comment by mike-engel** [comment]
Fixed with c09ea1f7393c94f7e35a3c578e3f7fdff539c3a9
