### ISSUE TITLE
publish demo to gh-pages

### ISSUE THREAD

**Issue by klaemo** [datuhealth/ampersand-floatinglabel-input-view#3]
hey,
could publish the demo site on gh-pages, so potential users (me! ;-)) can easily check it out? 

thanks

**Comment by mike-engel** [comment]
@klaemo I'll have to edit that demo, as it was for the original ampersand-input-view repo. Probably a couple days from now. Thanks for the catch though!

**Comment by klaemo** [comment]
Thanks! no hurry, though :)

---
Clemens

**Comment by mike-engel** [comment]
Closing this issue as this project is no longer being maintained.
